import React,{useCallback,useEffect,useLayoutEffect,useRef,useState}from'react';
import ResearchScreen from './ResearchScreen';
import TuningScreen from './TuningScreen';
import FirstOutputScreen from './FirstOutputScreen';
import ComparisonScreen from './ComparisonScreen';
import DetailComparisonScreen from './DetailComparisonScreen';
import PostSchedulerScreen from './PostSchedulerScreen';
import OrbitLeadScreen from './OrbitLeadScreen';
import AigptsCoverScreen from './AigptsCoverScreen';
import AigptsResearchScreen from './AigptsResearchScreen';
import {AigptsNeedsScreen,AigptsArchitectureScreen,AigptsStyleScreen} from './AigptsSystemScreens';
import {AigptsProductIntroScreen,AigptsComponentsScreen} from './AigptsProductScreens';
import {AigptsWorkbenchScreen,AigptsPricingScreen,AigptsChatScreen,AigptsMultimodalScreen,AigptsMusicScreen,AigptsHeadshotScreen,AigptsEditorScreen,AigptsMeetingScreen,AigptsSpeechScreen,AigptsPdfScreen,AigptsQrScreen,AigptsMoreScreen} from './AigptsCreationScreens';
import {TranslatorCoverScreen,TranslatorBannerScreen,DialectScreen,LiveTranslateScreen,TranslatorGalleryScreen} from './MobileTranslatorScreens';
import {SweetkeyCoverScreen,SweetkeySceneScreen,SweetkeyTagsScreen,SweetkeyRepliesScreen,SweetkeyGalleryScreen} from './MobileSweetkeyScreens';
import {ArtyCoverScreen,ArtyOverviewScreen,ArtyToolsScreen,ArtyCreationScreen,ArtyGalleryScreen} from './MobileArtyScreens';
import {HumanCoverScreen,HumanIntroScreen,HumanVideoScreen,HumanChatScreen,HumanGalleryScreen} from './MobileHumanScreens';
import {CampusCoverScreen,CampusEcosystemScreen,CampusClassScreen,CampusLeaveScreen,CampusBullyingScreen,CampusDormScreen,CampusCardScreen,CampusExamScreen,CampusFaceScreen,CampusStudentScreen} from './CampusScreens';
import {CampusOverviewScreen,BehaviorBoardScreen,DispatchBoardScreen,ControlBoardScreen,AigcPosterScreen,AigcPopupScreen,AigcBannerScreen,ContactScreen} from './FinalScreens';
import {HomeScreen,AboutScreen,DirectoryScreen,WorkflowCoverScreen,WorkflowCompareScreen,WorkflowSystemScreen,WorkflowStepsScreen,WorkflowTransitionScreen} from './IntroScreens';
import{createRoot}from'react-dom/client';import'./style.css';import'./override.css';
const nums=['01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','18','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35','36','38','39','40','41','42','43','44','45','46','47','48','49','50','51','52','53','54','55','56','57','59','60','61','62','63','64','65','66','67','68','69','70','71','72','73','74','75','76'];
const titles=['你好 我是李凯乐','关于我 / 经历与项目','作品集目录 / 四个章节','AIGC 时代，新的工作流','从设计执行到工作流驱动','AI 驱动 UI 设计工作流','产品与需求分析','From Workflow to Product','AI Agent 调研与分析','设计系统 / Color Primitives','AI 生成页面探索','Video Downloader 设计实践','页面方案 / 体验验证','生成后的设计优化','社交媒体产品 UI','WhatsApp CRM 产品 UI','AI 集合站 · 一站式 AI 工具','AI GPTs 产品定义','用户特征 / 需求洞察','信息架构','色彩 / 字体系统','AI GPTs 产品介绍','核心组件 / 视觉语言','一站式 AI 创作工作台','商业化组件','AI Chat','AI Image / AI Video','AI Music','AI Professional Headshots','Image Editing','AI Meeting Notes','Text / Audio Conversion','PDF Tools','QR Code Generator','More Features','随身翻译助手','多场景功能入口','方言翻译','实时对话翻译','翻译产品 UI 展示','Sweetkey','浪漫聊天语境 / 标签系统','自定义标签','自定义回复','Sweetkey UI 展示','Arty me','核心视觉 / 内容模块','AI 工具箱','AI 创作','Arty me UI 展示','虚拟数字人','数字人功能介绍','数字人视频','DeepSeek Chat','数字人 UI 展示','轻舟智慧校园','平台生态','班级管理','请假管理','防霸凌系统','宿舍管理','校园卡','考试管理','人脸识别','学生画像','异常预警','行为识别可视化','调度中心','一体化管控平台','AIGC 运营设计','AIGC 弹窗设计','AIGC Banner 设计','感谢观看 / 联系'];
const pages=nums.map((n,i)=>({n,title:titles[i],theme:(Number(n)>=32&&Number(n)<=36)||(Number(n)>=38&&Number(n)<=57)||(Number(n)>=59&&Number(n)<=69)?'light':'dark',section:n==='01'||n==='03'?0:n==='02'?1:Number(n)<18?2:Number(n)<38?3:Number(n)<59?4:Number(n)<76?5:6}));
const nav=['李凯乐 / 2026','关于我','AI 工作流','海外 Web','移动 APP','B端与 AIGC','联系'],navTargets=[0,1,3,16,35,55,72];
const footerLabels=['作品集首页','关于我 · 返回作品索引 ↗','AI 工作流 · 返回作品索引 ↗','海外 Web · 返回作品索引 ↗','移动 APP · 返回作品索引 ↗','B端与 AIGC · 返回作品索引 ↗','联系'];
function Home(){return <section className="home-content"><div className="home-copy"><small>LI KAILE · PORTFOLIO 2026</small><h1>你好 我是李凯乐</h1><h2>AI 原生 UI/UX 设计师</h2><p>我的作品涵盖海外 Web、移动 APP、B 端产品与 AI 工作流。从产品梳理、交互到视觉，探索想法如何成为可用的界面。</p><div className="home-actions"><button>浏览我的作品 ↗</button><button>关于我</button></div></div><div className="home-orbit"/></section>}
function Directory(){const cards=[['AI 工作流 × UI 设计','AI AGENT · UI WORKFLOW',['需求分析','AI Agent','UI生成','完善UI','Vibe Coding']],['海外 Web','GLOBAL WEB · UI DESIGN',['海外审美','响应式设计','高转化落地','多端适配','产品体验']],['移动 APP','MOBILE APP · UI DESIGN',['产品梳理','交互设计','视觉设计','启动图标','投放商店']],['B 端与 AIGC','B-END · AIGC · OTHER',['B端产品','数据大屏','AIGC视觉']]];return <section className="directory figma-directory"><h1>我的作品，从这里开始</h1><div className="directory-grid">{cards.map((c,i)=><article className={i===0?'selected':''} key={c[0]}><b>0{i+1}</b><h2>{c[0]}</h2><p>{c[1]}</p><div>{c[2].map(t=><span key={t}>{t}</span>)}</div></article>)}</div></section>}
function About(){return <section className="about figma-about"><aside className="profile"><div className="profile-image"><img src="/assets/figma/profile.png" alt="李凯乐"/></div><h1>李凯乐</h1><p>河北工程技术学院·本科</p><p>网络工程</p><p>16619792236</p><p>Banlili1020@163.com</p></aside><div className="experience"><article><h2>「工作经历」</h2><section><header><b>莱特摩比网络科技有限公司</b><time>2023.05–2026.08</time></header><ol><li>负责 Web、App 及 AI 产品的 UI/UX 设计，参与从需求分析、信息架构、交互流程、视觉设计到设计交付的完整产品设计流程；</li><li>将 Codex 融入日常 UI 设计工作流，实现从设计稿到可运行页面的快速验证，降低设计与开发之间的沟通成本。</li><li>实现“需求 → AI 方案探索 → UI 精修 → 前端实现 → 设计验证”的完整闭环。</li></ol></section><section><header><b>轻舟易联信息科技有限公司</b><time>2022.02–2023.05</time></header><ol><li>负责校园管理 B 端后台及小程序的 UI/UX 设计，完成页面、图标及相关视觉元素设计。</li><li>优化页面布局与交互流程，提升产品易用性和操作效率。</li></ol></section><section><header><b>西安真悦网络科技有限公司</b><time>2021.05–2022.01</time></header><ol><li>负责客户需求梳理与产品功能拆分，结合开发成本优化产品方案。</li><li>独立完成 APP UI/UX 设计、设计评审，并持续跟进设计落地与迭代。</li></ol></section></article><article><h2>「项目经历」</h2><section><header><b>出海项目 / WEB</b><time>莱特摩比网络科技有限公司</time></header><p>负责海外 Web 产品的 UI/UX 设计，项目涵盖 AI GPTs、会议纪要、AI 形象照、二维码生成、视频下载、PDF 工具等多个 AI 与效率工具类产品。</p></section></article></div></section>}
function MockVisual({kind,page}){const items=Array.from({length:kind==='workflow'?5:kind==='mobile'?3:6});return <div className={`mock ${kind}`}><div className="mock-bar"><i/><i/><i/><span>{page.title}</span></div><div className="mock-body">{kind==='workflow'&&<div className="flow-line"/>}{items.map((_,i)=><article key={i}><span>{String(i+1).padStart(2,'0')}</span><b>{kind==='mobile'?'PRODUCT SCREEN':kind==='dashboard'?'DATA MODULE':'DESIGN STEP'}</b><i/></article>)}</div></div>}
function CasePage({page}){const kind=Number(page.n)<18?'workflow':Number(page.n)<38?'dashboard':Number(page.n)<59?'mobile':Number(page.n)<73?'dashboard':'gallery';return <section className={`case-content ${kind}`}><div className="case-copy"><small>{page.n} · {page.section===1?'AI WORKFLOW':page.section===2?'GLOBAL WEB':page.section===3?'MOBILE APP':page.section===4?'B-END & AIGC':'PORTFOLIO'}</small><h1>{page.title}</h1><p>{kind==='workflow'?'从需求理解、信息组织到界面生成与验证，沉淀可复用的 AI 原生设计工作流。':kind==='mobile'?'围绕核心场景组织功能、内容与反馈，让复杂能力在移动端保持直观和轻盈。':kind==='dashboard'?'通过清晰的信息架构、组件系统与关键状态，构建完整且可扩展的产品体验。':'以系列化视觉语言组织内容，在统一品牌框架下保持每个创意的独立表达。'}</p><div className="case-tags"><span>PRODUCT DESIGN</span><span>UI SYSTEM</span><span>INTERACTION</span></div></div><MockVisual kind={kind} page={page}/></section>}
function WorkflowPage({n}){if(n==='04')return <section className="wf-cover"><img src="/assets/figma/screen04-visual.png" alt="AI 工作流视觉"/><div><h1>AI 改变的不是设计效率</h1><p>而是UI设计参与产品和解决问题的方式</p></div></section>;if(n==='05')return <section className="wf-compare"><h1>从「设计页面」到「设计系统与工作流」</h1><div className="compare-grid"><article><h2>之前 · 设计执行为主</h2><ul><li>产品输出原型后，UI 根据原型逐页完成视觉设计</li><li>大量时间投入页面绘制、组件搭建与重复调整</li><li>需求、设计、开发相对串行</li></ul></article><article><h2>现在 · 工作流驱动设计</h2><ul><li>设计更早参与需求分析与功能拆解</li><li>通过 AI 梳理结构、生成页面与交互方案</li><li>把重复工作沉淀为 Prompt、Skill 与 Agent</li></ul></article></div><div className="agent-window"><img src="/assets/figma/screen05-agent.png" alt="AI Agent"/><div><b>AI Agent</b><p>Analyzing competitor assets...</p><p>Extracting feature architecture...</p><p>Generating PRD...</p><p>Building Figma structure...</p></div></div></section>;if(n==='06')return <section className="wf-system"><header><h1>AI 驱动 UI 设计工作流</h1><p>从调研、竞品分析、需求拆解到 UI 生成与最终调优，将 Codex、Skill、MCP 与 Figma 串联成完整设计流程。</p></header><div className="wf-system-body"><img src="/assets/figma/screen06-workflow.png" alt="AI 驱动工作流"/><div>{['把数据变成可视化','把截图变成产品','从想法到网站','把想法变成APP','把PRD变成页面'].map(x=><span key={x}>{x}</span>)}</div></div></section>;if(n==='07'){const steps=[['1.想法 / 需求输入','记录核心想法，明确产品目标与基础需求'],['2.调研与竞品分析','通过 Codex 调研市场，分析竞品、用户评论与真实痛点'],['3.需求拆解 / PRD','整理功能优先级，输出页面清单、流程与需求文档'],['4.AI 生成 UI','通过 Skill / MCP / Figma Make / Stitch，快速生成高保真初稿'],['5.设计调优','人工 + AI 联合优化视觉、布局、组件与交互细节'],['6.验证与交付','检查完整流程与多状态，输出最终 UI 与开发交付稿']];return <section className="wf-steps"><h1>AI 工作流 × UI 设计</h1><div className="step-track">{steps.map((s,i)=><article key={s[0]}><b>{s[0]}</b><p>{s[1]}</p>{i<4&&<img src={`/assets/figma/screen07-${['a','b','c','d'][i]}.png`} alt=""/>}</article>)}</div></section>}return <section className="wf-transition"><img src="/assets/figma/screen08-visual.png" alt="From Workflow to Product"/><div><h1>From Workflow to Product</h1><h2>AI 工作流 · 产品实践</h2><p>From Research to UI Delivery</p><span>从调研、需求分析到 UI 生成与最终交付</span></div></section>}
function WorkflowPractice({page}){const n=page.n;if(n==='09')return <section className="practice agent-research"><div className="prompt"><h1>AI Agent 调研与分析</h1><p>你现在是一名资深产品经理 + UX 研究员 + UI/UX 设计师。</p><ol><li>完整分析竞品定位、目标用户与核心场景</li><li>拆解功能、页面结构、操作流程与信息架构</li><li>搜索用户反馈并聚类真实痛点</li><li>输出可落地的产品需求文档和 Figma 原型</li></ol></div><div className="research-stack"><img src="/assets/figma/s09-1.png" alt="竞品研究"/><img src="/assets/figma/s09-2.png" alt="用户洞察"/><div>{['Analyzing competitor assets...','Extracting feature architecture...','Searching user feedback...','Generating PRD...','Building Figma structure...'].map(x=><span key={x}>{x}</span>)}</div></div></section>;if(n==='10'){const colors=['#000','#090b10','#151923','#252b38','#3b4352','#596273','#7d8798','#a8b0bd','#d0d5dc','#eef1f5','#fff','#ff3948','#ffb020','#875cff','#29d17d'];return <section className="practice tokens"><header><h1>Codex+Figma输出规范</h1><p>Color</p></header><div className="palette"><h2>Primitive palette</h2>{colors.map((c,i)=><article key={c}><i style={{background:c}}/><b>{i<11?`neutral/${i===0?'black':950-i*100}`:['brand/red','accent/amber','accent/purple','status/success'][i-11]}</b><span>{c}</span></article>)}</div><div className="semantic"><h2>Semantic colors</h2>{['bg/canvas','bg/surface','bg/elevated','bg/brand','text/primary','text/secondary','text/muted','text/on-brand'].map(x=><p key={x}>color/{x}<span>var(--ds-color-{x.replace('/','-')})</span></p>)}</div></section>};if(n==='14')return <section className="practice tuning"><div><h1>AI 生成后的设计调优</h1><p>Codex + Figma 可以快速完成页面结构和基础视觉，但首版结果并不等于最终设计。</p>{[['01','结构优化'],['02','视觉优化'],['03','交互优化'],['04','细节收敛']].map(x=><article key={x[0]}><b>{x[0]}｜{x[1]}</b><span>{x[1]==='结构优化'?'调整页面层级、模块顺序与信息密度。':x[1]==='视觉优化'?'统一色彩、字体、间距、圆角与组件风格。':x[1]==='交互优化'?'补充状态、反馈与操作细节。':'通过多轮对比与修改达到真实交付标准。'}</span></article>)}</div><img src="/assets/figma/s14.png" alt="设计调优界面"/></section>;const visualMap={12:['s12-1.png','s12-2.jpg'],13:['s13-1.png','s13-2.png'],15:['s15-1.png','s15-2.png'],16:['s16-1.png','s16-2.png']};const names={11:'AI 生成页面探索',12:'Video Downloader 设计实践',13:'页面方案 / 体验验证',15:'社交媒体产品 UI',16:'WhatsApp CRM 产品 UI'};return <section className="practice product-practice"><header><small>AI WORKFLOW · PRODUCT PRACTICE</small><h1>{names[Number(n)]}</h1></header><div className="product-gallery">{(visualMap[Number(n)]||[]).map((x,i)=><img key={x} src={`/assets/figma/${x}`} alt={`${names[Number(n)]} ${i+1}`}/>)}{n==='11'&&Array.from({length:6},(_,i)=><article key={i}><span>GENERATED OPTION {String(i+1).padStart(2,'0')}</span><div/><b>{['结构探索','视觉方向','信息密度','交互状态','组件方案','最终选择'][i]}</b></article>)}</div></section>}
const webDescriptions={18:'从产品调研与设计分析，到 AI 工具发现与创作工作台，查看这套海外 Web 体验的设计过程与界面。',19:'面向创作者与效率用户的一站式 AI 原生创作平台，整合文本、图像、视频、音频与生产力工具。',20:'从多模态创作需求出发，以统一工作流降低工具切换成本，打造连续、高效的一站式 AI 创作平台。',21:'以 AI Chat、AI Image、AI Video、AI Music 为核心，覆盖多模态生成能力与高频效率工具。',22:'建立主题色、辅助色、背景色、线条色与字体层级，统一产品视觉语言。',23:'AIGPTS 面向内容创作者、设计师与营销人员，将主流 AI 模型和创作工具整合到统一工作空间。',24:'以卡片、导航、输入、按钮与状态组件构成一致、清晰且可扩展的视觉语言。',25:'统一整合模型选择、创作入口、项目内容与工具服务，完成从探索、生成到管理的完整流程。',26:'围绕套餐、额度、权益与转化场景建立一致的商业化组件。',27:'通过统一 AI Chat 入口整合多模型能力，降低多轮交互中的认知负担。',28:'支持文生图、图生图、文生视频、图生视频与视频生视频等多条创作路径。',29:'通过自然语言描述歌曲主题、风格、情绪与场景，生成旋律、歌词与完整音乐。',30:'基于用户照片生成多风格职业头像，覆盖商务、社交与个人品牌场景。',31:'集中多种 AI 图片编辑能力，通过清晰入口、任务分组与结果反馈减少操作路径。',32:'整合实时转写、AI 总结、重点提炼与待办生成，让会议内容从记录到执行形成闭环。',33:'整合文字转语音与语音转文字能力，支持配音、字幕、会议转写与内容整理。',34:'整合 PDF 转换、合并、拆分、压缩、编辑、OCR、签名与水印等高频能力。',35:'支持多种二维码类型，并提供样式、颜色、Logo 与 AI 艺术二维码定制。',36:'更多 AI 创作与效率工具，等待持续探索。'};
function WebCase({page}){const n=Number(page.n),hasImage=[18,19,20,23,24,25,26,27,28].includes(n);if(n===21)return <section className="web-architecture"><h1>信息架构分析</h1><div>{[['01','探索与项目管理架构'],['02','AI 创作架构'],['03','效率工具架构']].map(x=><article key={x[0]}><b>{x[0]}</b><h2>{x[1]}</h2><p>{webDescriptions[21]}</p></article>)}</div></section>;if(n===22)return <section className="web-colors"><header><h1>色彩规范定义</h1><p>Montserrat · Typography System</p></header><div className="color-bands">{['#9DFFBF','#30FF9C','#10F0FF','#8BF8FF','#45FFC3','#0E0E0E','#F8FF52','#FF8B37','#7042FF'].map(c=><i key={c} style={{background:c}}><span>{c}</span></i>)}</div></section>;return <section className={`web-case web-${n}`}><div className="web-copy"><small>OVERSEAS WEB · {page.n}</small><h1>{page.title}</h1><p>{webDescriptions[n]}</p>{n===18&&<a href="https://aigpts.ai/en">https://aigpts.ai/en ↗</a>}</div><div className="web-visual">{hasImage?<img src={`/assets/figma/p${n}.png`} alt={page.title}/>:<div className="generated-ui"><header/><aside/><main>{Array.from({length:6},(_,i)=><i key={i}/>)}</main></div>}</div></section>}
const mobileGroups={translator:{range:[38,42],name:'随身翻译助手',asset:'m38.png',desc:'面向日常沟通、出行与学习场景，支持方言、实时对话、拍照、文本与图片翻译。'},sweet:{range:[43,47],name:'Sweetkey',asset:'m43.png',desc:'面向社交与恋爱聊天场景，将标签化表达、个性化话术和快捷输入整合到智能键盘中。'},arty:{range:[48,52],name:'Arty me',asset:'m48.png',desc:'面向年轻用户的 AI 视觉创作 App，集 AI 视频、AI 头像与多种图片处理工具于一体。'},human:{range:[53,57],name:'虚拟数字人设计',asset:'m53.png',desc:'整合数字人形象生成、AI 口播、视频创作与智能对话能力，形成从形象创建到内容输出的一体化体验。'}};
function MobileCase({page}){const n=Number(page.n),group=Object.values(mobileGroups).find(g=>n>=g.range[0]&&n<=g.range[1]),cover=n===group.range[0];return <section className={`mobile-case ${cover?'mobile-cover':''}`}><div className="mobile-copy"><small>MOBILE APP · {page.n}</small><h1>{cover?group.name:page.title}</h1><p>{group.desc}</p>{cover&&<span>查看功能与交互 ↗</span>}</div><div className="phones">{cover?<img src={`/assets/figma/${group.asset}`} alt={group.name}/>:Array.from({length:n%3+3},(_,i)=><article key={i}><header><i/><b>{page.title}</b></header><main><div className="phone-hero"/><p>{['核心功能','使用场景','生成结果'][i%3]}</p>{Array.from({length:3},(_,j)=><span key={j}/>)}</main><footer/></article>)}</div></section>}
const bDescriptions={59:'轻舟校园是一套面向学校管理场景打造的智慧校园管理平台，覆盖学生、班级、宿舍、考试、请假、一卡通、人脸识别及校园安全等核心业务。',60:'连接学生、教师、家长和管理者，形成统一的平台生态与数据体系。',61:'通过班级树、学生列表和信息面板管理班级数据。',62:'覆盖请假申请、审批、记录和状态统计。',63:'通过风险视频、告警等级与处置记录建立校园防霸凌闭环。',64:'统一管理楼栋、入住、查寝和异常事件。',65:'整合校园卡状态、消费记录、充值与挂失操作。',66:'管理考试计划、考场、成绩与状态。',67:'实时查看识别记录、设备状态与异常告警。',68:'以基础档案、指标和行为趋势构建学生多维画像。',69:'汇总风险分类、趋势、事件与处置状态。',70:'通过指标、趋势、视频和事件列表呈现行为识别结果。',71:'统一调度事件、人员、资源与处置进度。',72:'综合呈现校园监控、业务指标、区域状态与实时事件。'};
function BCase({page}){const n=Number(page.n);if(n>=73)return <section className="aigc-show"><header><small>B-END & AIGC · {page.n}</small><h1>{page.title}</h1></header><img src={`/assets/figma/a${n}.png`} alt={page.title}/></section>;return <section className={`b-case b-${n}`}><div className="b-copy"><small>SMART CAMPUS · {page.n}</small><h1>{page.title}</h1><p>{bDescriptions[n]}</p></div><div className="dashboard-shell"><aside><b>轻舟智慧校园</b>{['总览','基础平台','学生事务','校园生活','校园安全'].map(x=><span key={x}>{x}</span>)}</aside><main><header><b>{page.title}</b><span>管理平台 v2.6</span></header><div className="metrics">{['今日数据','待处理','异常状态','完成率'].map((x,i)=><article key={x}><span>{x}</span><b>{[128,12,3,'96%'][i]}</b></article>)}</div><div className="charts"><article/><article/><article/></div></main></div></section>}
function Closing(){return <section className="closing figma-closing"><img src="/assets/figma/end.png" alt="联系视觉"/><div><small>LET’S CONNECT / 李凯乐</small><h1>让好想法，<br/>成为下一个好作品。</h1><p>感谢浏览我的作品。如果你正在寻找 UI/UX 设计师，欢迎和我聊聊。</p><a href="mailto:Banlili1020@163.com">邮件联系 ↗</a><span>16619792236 · Banlili1020@163.com</span></div></section>}
function Page({page}){
  const exact={
    '09':<ResearchScreen/>,'10':<ResearchScreen specification/>,'11':<FirstOutputScreen/>,
    '12':<ComparisonScreen/>,'13':<DetailComparisonScreen/>,'14':<TuningScreen/>,
    '15':<PostSchedulerScreen/>,'16':<OrbitLeadScreen/>,'18':<AigptsCoverScreen/>,
    '19':<AigptsResearchScreen/>,'20':<AigptsNeedsScreen/>,'21':<AigptsArchitectureScreen/>,
    '22':<AigptsStyleScreen/>,'23':<AigptsProductIntroScreen/>,'24':<AigptsComponentsScreen/>,
    '25':<AigptsWorkbenchScreen/>,'26':<AigptsPricingScreen/>,'27':<AigptsChatScreen/>,
    '28':<AigptsMultimodalScreen/>,'29':<AigptsMusicScreen/>,'30':<AigptsHeadshotScreen/>,
    '31':<AigptsEditorScreen/>,'32':<AigptsMeetingScreen/>,'33':<AigptsSpeechScreen/>,
    '34':<AigptsPdfScreen/>,'35':<AigptsQrScreen/>,'36':<AigptsMoreScreen/>,
    '38':<TranslatorCoverScreen/>,'39':<TranslatorBannerScreen/>,'40':<DialectScreen/>,
    '41':<LiveTranslateScreen/>,'42':<TranslatorGalleryScreen/>,
    '43':<SweetkeyCoverScreen/>,'44':<SweetkeySceneScreen/>,'45':<SweetkeyTagsScreen/>,
    '46':<SweetkeyRepliesScreen/>,'47':<SweetkeyGalleryScreen/>,
    '48':<ArtyCoverScreen/>,'49':<ArtyOverviewScreen/>,'50':<ArtyToolsScreen/>,
    '51':<ArtyCreationScreen/>,'52':<ArtyGalleryScreen/>,
    '53':<HumanCoverScreen/>,'54':<HumanIntroScreen/>,'55':<HumanVideoScreen/>,
    '56':<HumanChatScreen/>,'57':<HumanGalleryScreen/>,
    '59':<CampusCoverScreen/>,'60':<CampusEcosystemScreen/>,
    '61':<CampusClassScreen/>,'62':<CampusLeaveScreen/>,'63':<CampusBullyingScreen/>,
    '64':<CampusDormScreen/>,'65':<CampusCardScreen/>,'66':<CampusExamScreen/>,
    '67':<CampusFaceScreen/>,'68':<CampusStudentScreen/>,
    '69':<CampusOverviewScreen/>,'70':<BehaviorBoardScreen/>,'71':<DispatchBoardScreen/>,
    '72':<ControlBoardScreen/>,'73':<AigcPosterScreen/>,'74':<AigcPopupScreen/>,
    '75':<AigcBannerScreen/>,'76':<ContactScreen/>
  };
  if(exact[page.n])return exact[page.n];
  if(page.n==='01')return <HomeScreen/>;if(page.n==='02')return <AboutScreen/>;if(page.n==='03')return <DirectoryScreen/>;
  if(page.n==='04')return <WorkflowCoverScreen/>;
  if(page.n==='05')return <WorkflowCompareScreen/>;if(page.n==='06')return <WorkflowSystemScreen/>;if(page.n==='07')return <WorkflowStepsScreen/>;if(page.n==='08')return <WorkflowTransitionScreen/>;
  if(Number(page.n)>=9&&Number(page.n)<=16)return <WorkflowPractice page={page}/>;
  if(Number(page.n)>=18&&Number(page.n)<=36)return <WebCase page={page}/>;
  if(Number(page.n)>=38&&Number(page.n)<=57)return <MobileCase page={page}/>;
  if(Number(page.n)>=59&&Number(page.n)<=75)return <BCase page={page}/>;
  if(page.n==='76')return <Closing/>;return <CasePage page={page}/>;
}
function App(){const initial=Math.max(0,pages.findIndex(p=>`#screen-${p.n}`===location.hash));const[index,setIndex]=useState(initial),[old,setOld]=useState(null),[dir,setDir]=useState(1),[moving,setMoving]=useState(false);const navRef=useRef(null),current=pages[index],active=current.section;const go=useCallback(next=>{next=Math.max(0,Math.min(pages.length-1,next));if(next===index||moving)return;setDir(next>index?1:-1);setOld(index);setIndex(next);setMoving(true);history.replaceState(null,'',`#screen-${pages[next].n}`)},[index,moving]);useEffect(()=>{if(!moving)return;const t=setTimeout(()=>{setOld(null);setMoving(false)},660);return()=>clearTimeout(t)},[moving]);useLayoutEffect(()=>{const root=navRef.current,target=root?.querySelectorAll('button')[active];if(!root||!target)return;root.style.setProperty('--liquid-x',`${target.offsetLeft}px`);root.style.setProperty('--liquid-w',`${target.offsetWidth}px`)},[active]);useEffect(()=>{let lock=false;const wheel=e=>{if(lock||Math.abs(e.deltaY)<20)return;e.preventDefault();lock=true;go(index+(e.deltaY>0?1:-1));setTimeout(()=>lock=false,700)};const key=e=>{if(['ArrowDown','PageDown'].includes(e.key))go(index+1);if(['ArrowUp','PageUp'].includes(e.key))go(index-1)};addEventListener('wheel',wheel,{passive:false});addEventListener('keydown',key);return()=>{removeEventListener('wheel',wheel);removeEventListener('keydown',key)}},[go,index]);return <div className={`app theme-${current.theme} ${moving?'moving':''} dir-${dir>0?'up':'down'}`}><header className="glass-header"><nav ref={navRef}><i className="liquid-selector"/>{nav.map((label,i)=><button key={label} className={active===i?'active':''} onClick={()=>go(navTargets[i])}>{label}</button>)}</nav></header><main className="stage">{old!==null&&<div className="page-layer outgoing" data-theme={pages[old].theme}><Page page={pages[old]}/></div>}<div className={`page-layer ${moving?'incoming':''}`} data-theme={current.theme}><Page page={current}/></div></main><footer className="glass-footer"><button onClick={()=>go(index-1)} disabled={index===0}>↑ 上一屏</button><div className="liquid-progress"><span>{footerLabels[active]}</span></div><button onClick={()=>go(index+1)} disabled={index===pages.length-1}>下一屏 ↓</button></footer></div>}
createRoot(document.getElementById('root')).render(<App/>);
